"""Shared fixtures: a synthetic photo library with known metadata.

Photos are generated by stamping real EXIF tags onto tiny JPEGs with exiftool, so
the tests exercise the same code path as a real library without needing one.
"""

from __future__ import annotations

import base64
import shutil
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from photostats.core.exiftool import ExifTool, find_exiftool  # noqa: E402
from photostats.core.paths import Paths  # noqa: E402

# 1x1 JPEG, small enough to duplicate thousands of times.
TINY_JPEG = base64.b64decode(
    "/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a"
    "HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/wAALCAABAAEBAREA/8QAFAABAAAAAAAA"
    "AAAAAAAAAAAACf/EABQQAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQEAAD8AKp//2Q=="
)

CAMERAS = ["NIKON Z8", "NIKON Z8", "NIKON Z8", "Canon EOS R6", "Sony ILCE-7RM5"]
LENSES = ["NIKKOR Z 24-70mm f/2.8 S", "NIKKOR Z 24-70mm f/2.8 S", "RF 70-200mm F2.8",
          "FE 35mm F1.4 GM"]
ISOS = [100, 200, 400, 800, 1600, 3200]
SHUTTERS = [0.002, 0.004, 0.008, 0.016, 0.125, 0.5]
FSTOPS = [1.8, 2.8, 4.0, 5.6, 8.0]
FOCALS = [24, 35, 50, 70, 200]

#: Files created by :func:`make_library`, in a stable order.
LIBRARY: list[dict] = []


@pytest.fixture(scope="session", autouse=True)
def isolated_settings(tmp_path_factory):
    """Point every AppConfig in the suite at a throwaway ini file.

    QSettings on macOS writes to a plist in ~/Library/Preferences and ignores
    both setDefaultFormat and setPath, so redirecting it the documented way does
    not work. Swapping the class that constructs it does: without this, running
    the tests overwrites the real theme, language and recent-folder list.
    """
    qsettings = pytest.importorskip("PySide6.QtCore").QSettings
    from photostats.core import config as config_module

    scratch = tmp_path_factory.mktemp("settings")
    real = config_module.QSettings
    counter = [0]

    def isolated(*args, **kwargs):
        counter[0] += 1
        kwargs.pop("scope", None)
        return real(str(scratch / f"s{counter[0]}.ini"), qsettings.IniFormat)

    config_module.QSettings = isolated
    yield
    config_module.QSettings = real


@pytest.fixture(scope="session")
def exiftool_path() -> str:
    path = find_exiftool()
    if not path:
        pytest.skip("exiftool is not installed")
    return path


@pytest.fixture(scope="session")
def app_data(tmp_path_factory) -> Path:
    return tmp_path_factory.mktemp("appdata")


@pytest.fixture
def paths(app_data) -> Paths:
    return Paths(app_data_dir=app_data)


def _stamp(path: Path, tags: dict) -> None:
    with ExifTool(find_exiftool()) as tool:
        args = ["-overwrite_original"]
        for key, value in tags.items():
            args.extend([f"-{key}={value}"])
        args.append(str(path))
        tool.execute(args)


def make_library(root: Path, count: int = 40, with_pairs: bool = True) -> list[dict]:
    """Create *count* photos across a few folders with varied, known metadata."""
    root.mkdir(parents=True, exist_ok=True)
    folders = [root, root / "2024" / "mayo", root / "2024" / "junio", root / "vacaciones"]
    created: list[dict] = []
    with ExifTool(find_exiftool()) as tool:
        for index in range(count):
            folder = folders[index % len(folders)]
            folder.mkdir(parents=True, exist_ok=True)
            camera = CAMERAS[index % len(CAMERAS)]
            lens = LENSES[index % len(LENSES)]
            iso = ISOS[index % len(ISOS)]
            shutter = SHUTTERS[index % len(SHUTTERS)]
            fnumber = FSTOPS[index % len(FSTOPS)]
            focal = FOCALS[index % len(FOCALS)]
            month = 5 + (index % 3)
            day = 1 + (index % 27)
            fired = "On, Fired" if index % 5 == 0 else "Off, Did not fire"
            name = f"IMG_{4000 + index:04d}.jpg"
            path = folder / name
            path.write_bytes(TINY_JPEG)
            args = [
                "-overwrite_original",
                f"-Model={camera}",
                f"-LensModel={lens}",
                f"-ISO={iso}",
                f"-ExposureTime={shutter}",
                f"-FNumber={fnumber}",
                f"-FocalLength={focal}",
                f"-Flash={fired}",
                f"-DateTimeOriginal=2024:{month:02d}:{day:02d} 12:33:21",
                f"-CreateDate=2024:{month:02d}:{day:02d} 12:33:21",
                str(path),
            ]
            tool.execute(args)
            created.append({
                "path": path, "camera": camera, "lens": lens, "iso": iso,
                "shutter": shutter, "fnumber": fnumber, "focal": focal,
                "fired": index % 5 == 0, "month": month, "name": name,
            })
            # A RAW sibling for every third photo: only one of the pair counts.
            if with_pairs and index % 3 == 0:
                raw = folder / name.replace(".jpg", ".cr2")
                shutil.copy2(path, raw)  # same frame, RAW extension: RAW wins
                created.append({"path": raw, "companion": True})
    return created


@pytest.fixture
def library(tmp_path, exiftool_path) -> tuple[Path, list[dict]]:
    root = tmp_path / "photos"
    created = make_library(root, count=24)
    return root, created


@pytest.fixture
def empty_folder(tmp_path) -> Path:
    folder = tmp_path / "empty"
    folder.mkdir()
    return folder


def db_for(folder: Path, paths: Paths) -> Path:
    return paths.db_path(folder)
